export enum CnGrupoStatusEnum {
  OriginalDNN = 1,
  EmOrcamento,
  AguardandoCentral,
  EmitirCC,
  SaldoEmGrupo,
  CCEmAprovacao,
  CCReprovada,
  GrupoEncerrado,
  MapaEnviado,
  MapaRetornado,
  MapaExcluido,
  MapaReprovado,
  FichaAprovada,
  FichaReprovada,
  FichaEnviada,
  COEnviada,
  COEmitida,
  COTransacaoCancelada,
  CCTransacaoCancelada,
  CCAprovada,
  AguardandoCentralEEmitirCC,
  AguardandoDiretor,
  EnviadoparaAprovacaodoFornecedor,
}
