export enum RouteParamEnum {
  // IDS
  idCaderno = 'idCaderno',
  idChangeOrder = 'idChangeOrder',
  idCompraNegociacaoGrupo = 'idCompraNegociacaoGrupo',
  idCompraNegociacaoGrupoMapa = 'idCompraNegociacaoGrupoMapa',
  idCompraNegociacaoGrupoMapaFornecedor = 'idCompraNegociacaoGrupoMapaFornecedor',
  idDevolucaoProposta = 'idDevolucaoProposta',
  idEtapa = 'idEtapa',
  idFamilia = 'idFamilia',
  idFornecedor = 'idFornecedor',
  idGrupao = 'idGrupao',
  idGrupo = 'idGrupo',
  idProjeto = 'idProjeto',
  idOrcamento = 'idOrcamento',
  idOrcamentoCenarioFamilia = 'idOrcamentoCenarioFamilia',
  idOrcamentoCenarioGrupoContrato = 'idOrcamentoCenarioGrupoContrato',
  idOrcamentoChangeOrder = 'idOrcamentoChangeOrder',
  idOrcamentoGrupo = 'idOrcamentoGrupo',
  idOrcamentoGrupoClassificacao = 'idOrcamentoGrupoClassificacao',
  idOrcamentoGrupoItem = 'idOrcamentoGrupoItem',
  idOrcamentoGrupoItemKit = 'idOrcamentoGrupoItemKit',
  idOrcamentoCenario = 'idOrcamentoCenario',
  idOrcamentoFamilia = 'idOrcamentoFamilia',
  idPlanilha = 'idPlanilha',
  idPlanilhaHibrida = 'idPlanilhaHibrida',
  idPlanoCompraGrupo = 'idPlanoCompraGrupo',
  idPavimento = 'idPavimento',
  idProjetoEdificioPavimento = 'idProjetoEdificioPavimento',
  idUsuario = 'idUsuario',
  idOrcamentoGrupos = 'idOrcamentoGrupos',

  // TERMS
  customizada = 'customizada',
  interno = 'interno',
  planilha = 'planilha',
  readonly = 'readonly',
  supply = 'supply',
  visaoNegociacao = 'visaoNegociacao',
  index = 'index',
  paginaAtual = 'paginaAtual',
  totalPorPagina = 'totalPorPagina',
}
